### PR TITLE
JSX parser refactoring and improvements

### PR DESCRIPTION
**Pull request by elsassph**
- separated JSX parsing (AST building) from code emission,
- html entities replacement (#36),
- correct handling of whitespace (#38),
- error for adjacent JSX elements (#34),
- unit tests for JSX AST building and html entities replacement.

### CODE REVIEW

**Comment by elsassph** [comment]
Please review @zabojad @kevinresol @mcheshkov

**Comment by kevinresol** [comment]
Thanks!
Btw I decided to move react native to a separate lib. Because testing things like this requires me to merge branches, which gets very nasty sometimes.

**Comment by mcheshkov** [comment]
According to `https://www.w3.org/TR/html4/sgml/entities.html` and Wikipedia, HTML 4 have 250+ entities.
According to `https://dev.w3.org/html5/html-author/charref` html5 have 1.4k+ entites.
So I think you missed some)

`inikulin/parse5` is using `https://html.spec.whatwg.org/entities.json` (2231 entity) to generate trie for parsing, see [this](https://github.com/inikulin/parse5/blob/fefd045f7a7cf752bd554317f72c3458bcb5eeee/Gulpfile.js#L17)

**Comment by elsassph** [comment]
Thanks @mcheshkov, I couldn't find a good file so I had taken the smallest list I could find :)
I hope it won't cause performance issues during completion.

**Comment by elsassph** [comment]
@zabojad @kevinresol @mcheshkov before merging I need thumb ups from you guys that things don't break horribly. Are you able to give it a try? If so when? The main haxe-react codebase we have is not using JSX.

**Comment by kevinresol** [comment]
Have been using it, and looks like a :+1: for me.

**Comment by mcheshkov** [comment]
Will try tomorrow.

**Comment by mcheshkov** [comment]
It took longer than I expected, mostly because of package renaming. Hope to get some results today.

**Comment by elsassph** [comment]
I pushed a few fixes - in particular, Haxe display completion should work for string interpolation inside JSX.

**Pull request merged**
