### PR TITLE
@:pure for PureComponent + changes to ReactComponent

### PR DESCRIPTION
**Pull request by kLabz**
### Warning: this contains breaking changes

I started by removing string refs from `ReactComponent`, this api being considered "legacy" or even deprecated (by eslint at least).

This is the breaking change of this PR, since even if a project never uses `ReactComponentOfRefs` and such, `ReactComponentOfPropsAndState` has been removed in favor of just `ReactComponentOf<TProps, TState>`.

`ReactComponentOfPropsAndState` can be reactivated by using the `react_comp_legacy` compilation flag. `ReactComponentOfRefs` and such cannot be reactivated.

### Optional behavior: strict ReactComponentOf typing

One source of errors I have found in haxe-react projects, is having a `ReactComponentOfProps` and doing things with the state, which has then no typing (`Dynamic`) and can lead to disturbing code (the component appears to have no state, while in practice it has one).

I added, under the `react_comp_strict_typing` compilation flag, a simple fix to that: `ReactComponentOfProps` use `TVoid` as TState, and `ReactComponentOfState` use it as TProps. `TVoid` is an empty enum, so manipulating state on a ReactComponentOfProps should become impossible, as well as accessing props.

I can see one con with this feature: you'll need to have a TProps if you want to use `props.children`. **Maybe exposing children via a getter (in ReactComponent) returning `untyped props.children` could help here?** (and in other cases when we use children and do not want to add it to our TProps)

### Original feature of this PR: `@:pure`

Note: **maybe use `@:pureComponent` instead to avoid conflict with other features?**

The original purpose of this PR was to add support for PureComponents making use of haxe-react knowledge of our components. The previous points were just things I had in mind for a few months and having them simplified the work for this feature.

Adding a `@:pure` meta to your component class, a `shouldComponentUpdate` will be added. The content of this function will depend on your TProps and TState:
 * If both TProps and TState are defined (not TVoid), this will have the same behavior as React's PureComponent (shallowCompare on both props and state)
 * If only TProps or TState is defined, only the props (resp. the state) will be shallowCompare'd
 * If somehow you have both TProps and TState being TVoid, the function will always return false without checking anything

Note that it will only be added if you haven't defined one yourself; **should it break instead of doing nothing, with a compilation error/warning stating that this `@:pure` didn't do anything?**

### Notes

 * This PR should at least be updated by adding documentation to the README file about those changes.
 * This includes a [small commit](https://github.com/massiveinteractive/haxe-react/commit/d679eb39fb03c966140abe6c96eac9a9bc92589f) I had in my local version for handling `jsx('')` (with empty string) without breaking with an unclear error message.

### CODE REVIEW

**Comment by mikicho** [comment]
Great PR!
I'd suggest to use `@:pureReactComponent`, like `ReactComponent`

**Comment by kevinresol** [comment]
In fact I would suggested renaming `ReactComponent` to `Component`, to better match the original API.

**Comment by mikicho** [comment]
Haxe does not support an alias, so 'Component' is too broad term isn't?

**Comment by kevinresol** [comment]
That is the work of namespaces (packages).
And Haxe does support alias.

**Comment by mikicho** [comment]
Yeah, but if you have two classes in the same name, you have to write the full namespace everywhere in your class/page/package

**Comment by kLabz** [comment]
Or you can use an alias for one (or both). Plus I don't see many use cases when you need both a Component (ReactComponent) and another non-react Component type in the same class. But if that happens, you can still `import react.Component as ReactComponent`.

I'm not sure about that change, though. Sure it would be prettier, but that would also break all existing haxe-react code (well, we could still provide both Component and ReactComponent) and I'm not sure the gain is enough to justify the loss.

**Comment by mikicho** [comment]
WHAT? Since when we have an alias in Haxe? Cool!
Anyway, I think we just need, for now, to do something like:
`typedef Component = ReactComponent;`

**Comment by kLabz** [comment]
Well, we've had the `as` syntax since october 2014, but we had `import react.Component in ReactComponent` before that and I don't remember a time when we didn't have this feature :)

Not sure if the typedef alone would be enough because of all the macros, I'd need to check.

**Comment by elsassph** [comment]
Stricter typing and (let's go crazy) classes renaming could go in a 2.x branch.

1.x should just add a `PureComponent` extern, and we should consider keeping it in 2.x to make it easier to get into haxe-react. Extending `PureComponent` allows to have a local implementation of `shouldComponentUpdate` and still be able to call `super.shouldComponentUpdate` for the default implementation.

**Comment by kLabz** [comment]
If we're going crazy for 2.x, let's add TProps <-> PropTypes bindings and jsx props strict typing too o/

Do you want the TRefs removal on 1.x?

**Comment by elsassph** [comment]
TRefs removal can be considered for 1.x - it should hopefully be a minor regression risk.

**Pull request closed without merging**
