### PR TITLE
Better positions

### PR DESCRIPTION
**Pull request by kevinresol**
Better error position reporting:

1. when there is syntax error in the xml itself, the err pos will correctly pinpoint the problematic xml
2. when there is typing error (unknown identifier, etc), the err pos will point to the jsx call (we cannot pinpoint the position in the xml because the xml parser doesn't store the pos after it finishes parsing)

### CODE REVIEW

**Comment by elsassph** [comment]
I'm afraid this isn't compatible with Haxe 3.2.1

**Comment by kevinresol** [comment]
Oh sorry, I didn't test on 3.2.1. Which part will break actually?

**Comment by elsassph** [comment]
The parser doesn't raise an error object before 3.3: the exception class doesn't even exist.

**Comment by kevinresol** [comment]
Let's see if this does the trick.

**Pull request merged**
