### PR TITLE
Strictly typing for the props in React.createElement()

### PR DESCRIPTION
**Pull request by kevinresol**
This make sure the props are properly typed.

### CODE REVIEW

**Comment by kevinresol** [comment]
@elsassph I have fixed it, but I think I somehow messed up the commits.

You may want to close this and make the changes in your PR #21 

basically only need to change `createElement()` to the following:

``` haxe
public static function createElement<P, T:Class<ReactComponentOfProps<P>>>(type:EitherType<T, String>, ?attrs:P, children:Rest<Dynamic>):ReactComponent;
```

**Comment by elsassph** [comment]
I see, still it might be a breaking change so it'd be better if you could create a new branch off master since things have been merged and ask people who have complex JSX projects to try it.

**Comment by kevinresol** [comment]
@elsassph I am not sure if I can make a PR which creates a branch in this repo. As I said, it is just a one-line change (with the related imports). So please feel free to take it and add it as you wish to.

``` haxe
public static function createElement<P, T:Class<ReactComponentOfProps<P>>>(type:EitherType<T, String>, ?attrs:P, children:Rest<Dynamic>):ReactComponent;
```

**Comment by kevinresol** [comment]
Any updates here?

**Comment by elsassph** [comment]
We are a bit unsure about the consequences in some existing codebase. Eg. it may not be retro compatible with some projects. We need to test it on internal projects but we're only updating to the latest changes.

**Comment by kevinresol** [comment]
I think this change is necessary. Afterall people use haxe because it is strongly typed. I think we can enable this by default but add a compiler flag to disable.

**Comment by elsassph** [comment]
We'll do it, just after the inline element generation (did you check this PR?)

**Comment by zabojad** [comment]
ah, great to see that this PR will finally be integrated. +1 for props types checking :)!

**Comment by kevinresol** [comment]
@elsassph I am not using this PR at the moment. (because I am on the literal branch and didn't manually integrate this PR) But I have tested it when I wrote it. It should work.

**Comment by elsassph** [comment]
Good to hear you're trying the inline elements PR - it needs serious testing.

**Comment by zabojad** [comment]
Guys, it seems this PR hasn't been merged yet. Can we reopen it or at least create a new branch so that we can all test it properly?

**Comment by elsassph** [comment]
Yes, in fact we need I believe to change the return type of `createElement`: it's not returning a `ReactComponent` technically, but just the VDOM information. In fact it can also be just a `String` so we need something that can reconciliate them.

**Pull request closed without merging**
